- name: common tasks
  include_tasks: ./common.yaml

- name: hdfs tasks
  include_tasks: ./hdfs.yaml

- name: yarn tasks
  include_tasks: ./yarn.yaml

- name: mapred tasks
  include_tasks: ./mapred.yaml

- name: sssd tasks
  include_tasks: ./sssd.yaml
